import { contextBridge, ipcRenderer } from 'electron'
import { Channels } from './windows/channels'

contextBridge.exposeInMainWorld('mainWindow', {
	minimize: () => ipcRenderer.send(Channels.Main.minimize),
	maximize: () => ipcRenderer.send(Channels.Main.maximize),
	unmaximize: () => ipcRenderer.send(Channels.Main.unmaximize),
	openSettingWindow: () => ipcRenderer.send(Channels.Main.openSetting),
	openDevtools: () => ipcRenderer.send(Channels.Main.openDevtools),
	close: () => ipcRenderer.send(Channels.Main.close),
	reload: () => ipcRenderer.send(Channels.Main.reload),
	onMinimize: callback => ipcRenderer.on(Channels.Main.onMinimize, callback),
	onMaximize: callback => ipcRenderer.on(Channels.Main.onMaximize, callback),
	onUnMaximize: callback => ipcRenderer.on(Channels.Main.onUnmaximize, callback),
	onError: callback => ipcRenderer.on(Channels.Main.onError, (e, ...args) => callback(...args)),
	getAppTheme: () => ipcRenderer.sendSync(Channels.Main.getAppTheme),
	setAppTheme: (...args) => ipcRenderer.send(Channels.Main.setAppTheme, ...args),
	getSystemLocale: () => ipcRenderer.sendSync(Channels.Main.getSystemLocale),
	getConfig: (...args) => ipcRenderer.sendSync(Channels.Main.getConfig, ...args),
	setConfig: (...args) => ipcRenderer.send(Channels.Main.setConfig, ...args),
	pinia: {
		change: (...args) => ipcRenderer.send(Channels.Main.pinia.change, ...args),
		onChange: callback => ipcRenderer.on(Channels.Main.pinia.onChange, (e, ...args) => callback(...args)),
	},
	redis: {
		create: (...args) => ipcRenderer.invoke(Channels.Main.redis.create, ...args),
		connect: (...args) => ipcRenderer.invoke(Channels.Main.redis.connect, ...args),
		disconnect: (...args) => ipcRenderer.invoke(Channels.Main.redis.disconnect, ...args),
		destory: (...args) => ipcRenderer.invoke(Channels.Main.redis.destory, ...args),
		isConnected: (...args) => ipcRenderer.sendSync(Channels.Main.redis.isConnected, ...args),
		ping: (...args) => ipcRenderer.invoke(Channels.Main.redis.ping, ...args),
		configGet: (...args) => ipcRenderer.invoke(Channels.Main.redis.configGet, ...args),
		select: (...args) => ipcRenderer.invoke(Channels.Main.redis.select, ...args),
		info: (...args) => ipcRenderer.invoke(Channels.Main.redis.info, ...args),
		keys: (...args) => ipcRenderer.invoke(Channels.Main.redis.keys, ...args),
		set: (...args) => ipcRenderer.invoke(Channels.Main.redis.set, ...args),
		hset: (...args) => ipcRenderer.invoke(Channels.Main.redis.hset, ...args),
		get: (...args) => ipcRenderer.invoke(Channels.Main.redis.get, ...args),
		smembers: (...args) => ipcRenderer.invoke(Channels.Main.redis.smembers, ...args),
		hget: (...args) => ipcRenderer.invoke(Channels.Main.redis.hget, ...args),
		del: (...args) => ipcRenderer.invoke(Channels.Main.redis.del, ...args),
		hdel: (...args) => ipcRenderer.invoke(Channels.Main.redis.hdel, ...args),
		rename: (...args) => ipcRenderer.invoke(Channels.Main.redis.rename, ...args),
		exists: (...args) => ipcRenderer.invoke(Channels.Main.redis.exists, ...args),
		expire: (...args) => ipcRenderer.invoke(Channels.Main.redis.expire, ...args),
		type: (...args) => ipcRenderer.invoke(Channels.Main.redis.type, ...args),
		ttl: (...args) => ipcRenderer.invoke(Channels.Main.redis.ttl, ...args),
		memoryUsage: (...args) => ipcRenderer.invoke(Channels.Main.redis.memoryUsage, ...args),
		srem: (...args) => ipcRenderer.invoke(Channels.Main.redis.srem, ...args),
		sadd: (...args) => ipcRenderer.invoke(Channels.Main.redis.sadd, ...args),
		onReady: callback => ipcRenderer.on(Channels.Main.redis.onReady, (e, ...args) => callback(...args)),
		onError: callback => ipcRenderer.on(Channels.Main.redis.onError, (e, ...args) => callback(...args)),
		onEnd: callback => ipcRenderer.on(Channels.Main.redis.onEnd, (e, ...args) => callback(...args)),
		onConnect: callback => ipcRenderer.on(Channels.Main.redis.onConnect, (e, ...args) => callback(...args)),
		onReconnect: callback => ipcRenderer.on(Channels.Main.redis.onReconnect, (e, ...args) => callback(...args)),
	},
})

contextBridge.exposeInMainWorld('settingWindow', {
	close: () => ipcRenderer.send(Channels.Setting.close),
	minimize: () => ipcRenderer.send(Channels.Setting.minimize),
})
